apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app-deploy
  labels:
    app: medicure-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-app
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-app-container
        image: shinojc/medicure
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-np-service
  labels:
    app: medicure-app
spec:
  selector:
    app: medicure-app

  type: NodePort
  ports:
  - nodePort: 31033    
    port: 8082
    targetPort: 8082
